/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:37924d63-6550-4f05-a776-c76baeba0893",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_owzpvOsCs",
    "aws_user_pools_web_client_id": "46skpdaj61s7rc02akiqvmiqan",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "weddingphotos88eabba96952425d94fe755a395c97f367aa0-dev",
    "aws_user_files_s3_bucket_region": "eu-central-1"
};


export default awsmobile;
